# Bonsai Configuration File

# Values will change here if changed in app

# -----------------------
# Sidebar Settings
# -----------------------
SIDEBAR_GROWTH_THRESHOLD_PERCENTAGE = 0.2   # Show size changes above this percentage
SIDEBAR_WIDTH = 40

SIDEBAR_SELECTED_FOLDER_ICON = ""
SIDEBAR_SELECTED_FILE_ICON = ""
SIDEBAR_FOLDER_ICON = ""
SIDEBAR_FILE_ICON = ""
SIDEBAR_BACK_ICON = ""

SIDEBAR_GROWTH_COLOR = {255, 175, 95}
SIDEBAR_SHRINK_COLOR = {95, 125, 255}

# -----------------------
# Chart Settings
# -----------------------
CHART_MAX_SIZE_THRESHOLD_PERCENTAGE = 2     # Minimum % usage shown in pie chart
CHART_MAX_GENERATIONS = 4                   # Max rings in pie chart
CHART_DIM_FACTOR = 0.15                     # Dimming factor for child slices

# One color per line: {R, G, B}
CHART_COLORS = [
    {255, 99, 71},                          # Tomato Red
    {30, 144, 255},                         # Dodger Blue
    {60, 179, 113},                         # Medium Sea Green
    {255, 165, 0},                          # Orange
    {186, 85, 211},                         # Medium Orchid
    {255, 215, 0},                          # Gold
    {70, 130, 180},                         # Steel Blue
    {255, 105, 180},                        # Hot Pink
    {154, 205, 50},                         # Yellow Green
    {255, 140, 0}                           # Dark Orange
]
